server:
  port: 80
  tomcat:
    additional-tld-skip-patterns: "serializer.jar"
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    database: oracle
    hibernate:
      ddl-auto: none
    open-in-view: false           # JPA 를 사용하는 프로젝트는 반드시 open-in-view 속성을 false 로 지정하세요.
  datasource:
    nhcerp:
      driver-class-name: com.tmax.tibero.jdbc.TbDriver
      jdbc-url: jdbc:tibero:thin:@192.168.0.28:8629:tibero
      username: nhcerp
      password: nhcerp1215
      hikari:
        connection-timeout: 300000
        max-pool-size: 10
        max-lifetime: 200000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: nhc.erp
prunus:
  websquare:
    adaptor:
      websquare-home: C:\Development\runtime\websquare_home
  security:
    authentication:
      tenant: nhc
      username-parameter: username
      password-parameter: password
      maximum-password-age: 90      # 비밀번호 유효기간
      maximum-failed-attempts: 5
      lock-time-duration: 3600000   # 1시간
      mode: session      
    access:
      whitelisted-endpoints:
        - /**
        - /error
        - /I18N
      ignored-static-endpoints:
        - /**/*.html
        - /websquare/**
        - /resources/**
        - /webjars/**
  persistence:
    data:
      audit:
        modify-on-create: true
    mybatis:
      audit.enabled: true
      pagination.enabled: true
logging:
  level:
    nhc.erp: debug
    prunus: debug
    org.hibernate.SQL: info
    root: info
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.transaction: debug
    org.springframework.jdbc.datasource: debug
    org.springframework.jdbc.support: debug
    com.zaxxer.hikari.pool.HikariPool: debug

---

spring:
  config:
    activate:
      on-profile: dev, prod
prunus:
  websquare:
    adaptor:
      websquare-home: