server:
  port: 8080
  tomcat:
    additional-tld-skip-patterns: "serializer.jar"
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    database: oracle
    hibernate:
      ddl-auto: none
    open-in-view: false           # JPA 를 사용하는 프로젝트는 반드시 open-in-view 속성을 false 로 지정하세요.   
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: nhc.erp
prunus:
  websquare:
    adaptor:
      websquare-home: C:\Development\runtime\websquare_home
  security:
    authentication:
      tenant: nhc
      username-parameter: username
      password-parameter: password
      maximum-password-age: 90      # 비밀번호 유효기간
      maximum-failed-attempts: 5
      lock-time-duration: 3600000   # 1시간
      mode: SESSION      
    access:
      whitelisted-endpoints:
        - /**
        - /error
        - /I18N
      ignored-static-endpoints:
        - /**/*.html
        - /websquare/**
        - /resources/**
        - /webjars/**
  persistence:
    data:
      audit:
        modify-on-create: true
    mybatis:
      audit.enabled: true
      pagination.enabled: true
  multi-datasource:
    primary: nhcerp
    private-key: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAtq4B+v/RnQ1yJm1Vz0QKPs+fxANBF1cnuAwYbj5O0/EvvC90SUye0m/M3FQrlliVAC/xGDZCBj5RsCcVDP1y7wIDAQABAkA2ojPVbUyzO6I3+9r98ctenZmadZ6x7E7krDliPyA0IhwJcizN4cCat3OJVEWLRR/PBWfELvqtY5lL3QIKddCBAiEA5/AS05uQfObqT98m1sP18fz6UK3DgskmaPaaa4mcx+UCIQDJobZa4PQop0nzrd8wDCIgWJ0xHQmlKePJLQhny8p6QwIgPM+uL/smrAjjQGPSzBZ/Ap6Ahuy4SS8yOe0GWdGv4J0CIQC34sSFIy1pOhAmrUaj8hzZdRd+6CWYvJhiK7DDwMbbMwIgZwdHQzO9ygVoNjzP4rmTkJrsB6xqJOSBMp2P4TVSXkk=
    strict: true
    p6spy:
      enabled: true
    datasources:
      nhcerp:      # 데이터소스 이름
        driver-class-name: com.tmax.tibero.jdbc.TbDriver
        url: jdbc:tibero:thin:@192.168.0.28:8629:tibero
        username: nhcerp
        password: ENC(BJcc76rTcnUIX9KJsw0TSTjbVtOEF5E+gzhBzCI73dn9uw5dgFyB/ufkS+XtGInLtX+3cUr10kaYOe1eszE+pA==)
        p6spy: true
#      wrm:        # 데이터소스 이름
#        driver-class-name: org.mariadb.jdbc.Driver
#        url: jdbc:mariadb://127.0.0.1:3306/WRM
#        username: APP
#        password: ENC(Jq8aLfq8FXWmO1re2M3A1aZztlg0ShF7y9QItZhcbMKkQYMKlKL7TY5G91FmF95QtUSYuWDMCk3vNVhInzb3Xg==)
#        p6spy: true
logging:
  level:
    nhc.erp: info
    prunus: debug
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.transaction: debug
    org.springframework.jdbc.datasource: debug
    org.springframework.jdbc.support: debug
    com.zaxxer.hikari.pool.HikariPool: debug

---

spring:
  config:
    activate:
      on-profile: dev, prod
prunus:
  websquare:
    adaptor:
      websquare-home: