server:
  port: 80
  tomcat:
    additional-tld-skip-patterns: "serializer.jar"
spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/labor
#    username: sa
#    password:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: nhc.erp
prunus:
  websquare:
    adaptor:
      websquare-home: C:\Development\runtime\websquare_home
  security:
    authentication:
      tenant: labor
      username-parameter: username
      password-parameter: password
      maximum-password-age: 90 # 비밀번호 유효기간
      maximum-failed-attempts: 5
      lock-time-duration: 3600000 # 1시간
    access:
      whitelisted-endpoints:
        - /**
        - /error
        - /I18N
      ignored-static-endpoints:
        - /**/*.html
        - /websquare/**
        - /resources/**
        - /webjars/**
logging:
  level:
    nhc.erp: debug
    org.springframework.web: debug
    org.springframework.security: debug

---
spring:
  config:
    activate:
      on-profile: dev, prod
prunus:
  websquare:
    adaptor:
      websquare-home:
