server:
  port: 80
  tomcat:
    additional-tld-skip-patterns: "serializer.jar"
spring:
  sql.init.mode: embedded # always, embedded, never
  datasource.hikari:
    tibero:
      driver-class-name: com.tmax.tibero.jdbc.TbDriver
      jdbc-url: jdbc:tibero:thin:@192.168.0.28:8629:tibero
      username: nhcerp
      password: nhcerp1215
  data.web.pageable:
    default-page-size: 10
    one-indexed-parameters: true # page number 를 '1'부터 시작한다. (default : false, start at 0)
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: nhc.erp
prunus:
  websquare:
    adaptor:
      websquare-home: C:\Development\runtime\websquare_home
  security:
    authentication:
      tenant: labor
      username-parameter: username
      password-parameter: password
      maximum-password-age: 90      # 비밀번호 유효기간
      maximum-failed-attempts: 5
      lock-time-duration: 3600000   # 1시간
    access:
      whitelisted-endpoints:
        - /**
        - /error
        - /I18N
      ignored-static-endpoints:
        - /**/*.html
        - /websquare/**
        - /resources/**
        - /webjars/**
  persistence:
    data:
      audit:
        modify-on-create: true
    mybatis:
      audit.enabled: true
      pagination.enabled: true
logging:
  level:
    nhc.erp: debug
    org.springframework.web: debug
    org.springframework.security: debug

---

spring:
  config:
    activate:
      on-profile: dev, prod
prunus:
  websquare:
    adaptor:
      websquare-home: