CREATE SEQUENCE AUTHORITY_ROLE_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE PRUNUS_BIZ_AUTHORITY_ROLE
(
    AUTHORITY_ROLE_ID BIGINT NOT NULL,
    TENANT            VARCHAR(50) NOT NULL,
    NAME              VARCHAR(100) NOT NULL,
    ROLE              VARCHAR(50) NOT NULL,
    VOTER             VARCHAR(50) NOT NULL,
    DESCRIPTION       VARCHAR(500),
    ACTIVE            BOOLEAN NOT NULL,
    PRIMARY KEY (AUTHORITY_ROLE_ID)
);
ALTER TABLE PRUNUS_BIZ_AUTHORITY_ROLE ADD CONSTRAINT PRUNUS_BIZ_AUTHORITY_ROLE_UNIQUE_01 UNIQUE (TENANT, VOTER, ROLE);

CREATE SEQUENCE AUTHORITY_ROLE_MENU_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE PRUNUS_BIZ_AUTHORITY_ROLE_MENU
(
    AUTHORITY_ROLE_MENU_ID BIGINT NOT NULL,
    MENU_ID                BIGINT,
    AUTHORITY_ROLE_ID      BIGINT,
    PRIMARY KEY (AUTHORITY_ROLE_MENU_ID)
);

CREATE SEQUENCE AUTHORITY_ROLE_RESOURCE_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE PRUNUS_BIZ_AUTHORITY_ROLE_RESOURCE
(
    AUTHORITY_ROLE_RESOURCE_ID BIGINT NOT NULL,
    RESOURCE_ID                BIGINT,
    AUTHORITY_ROLE_ID          BIGINT,
    PRIMARY KEY (AUTHORITY_ROLE_RESOURCE_ID)
);

CREATE SEQUENCE RESOURCE_AUTHORITY_ROLE_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE PRUNUS_BIZ_RESOURCE_AUTHORITY_ROLE
(
    RESOURCE_AUTHORITY_ROLE_ID BIGINT NOT NULL,
    AUTHORITY_ROLE_ID          BIGINT,
    RESOURCE_ID                BIGINT,
    PRIMARY KEY (RESOURCE_AUTHORITY_ROLE_ID)
);
