CREATE SEQUENCE CODE_TYPE_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE PRUNUS_BIZ_CODE_TYPE
(
   CODE_TYPE_ID BIGINT NOT NULL,
   TENANT       VARCHAR(50) NOT NULL,
   NAME         VARCHAR(100),
   DESCRIPTION  VARCHAR(500),
   SORT_ORDER   INTEGER,
   ACTIVE       BOOLEAN NOT NULL,
   PRIMARY KEY (CODE_TYPE_ID)
);

CREATE SEQUENCE CODE_GROUP_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE PRUNUS_BIZ_CODE_GROUP
(
   CODE_GROUP_ID BIGINT NOT NULL,
   TENANT        VARCHAR(50) NOT NULL,
   CODE          VARCHAR(50) NOT NULL,
   NAME          VARCHAR(100) NOT NULL,
   CODE_TYPE_ID  BIGINT,
   DESCRIPTION   VARCHAR(500),
   ACTIVE        BOOLEAN NOT NULL,
   PRIMARY KEY (CODE_GROUP_ID)
);

CREATE SEQUENCE CODE_GROUP_DICTIONARY_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE PRUNUS_BIZ_CODE_GROUP_DICTIONARY
(
   CODE_GROUP_DICTIONARY_ID BIGINT NOT NULL,
   TITLE                    VARCHAR(100),
   LANGUAGE                 VARCHAR(10),
   CODE_GROUP_ID            BIGINT NOT NULL,
   PRIMARY KEY (CODE_GROUP_DICTIONARY_ID)
);

CREATE SEQUENCE CODE_ITEM_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE PRUNUS_BIZ_CODE_ITEM
(
   CODE_ITEM_ID         BIGINT NOT NULL,
   TENANT               VARCHAR(50) NOT NULL,
   CODE                 VARCHAR(50) NOT NULL,
   NAME                 VARCHAR(100) NOT NULL,
   DESCRIPTION          VARCHAR(500),
   SHORT_NAME           VARCHAR(100),
   SORT_ORDER           INTEGER,
   PARENT_CODE_GROUP_ID BIGINT,
   ATTR1                VARCHAR(255),
   ATTR2                VARCHAR(255),
   ATTR3                VARCHAR(255),
   ATTR4                VARCHAR(255),
   ATTR5                VARCHAR(255),
   ATTR6                VARCHAR(255),
   ATTR7                VARCHAR(255),
   ATTR8                VARCHAR(255),
   ATTR9                VARCHAR(255),
   ATTR10               VARCHAR(255),
   ACTIVE               BOOLEAN,
   CODE_GROUP_ID        BIGINT,
   CREATED_BY           VARCHAR(255),
   CREATED_DATE         TIMESTAMP,
   CREATED_REMOTE_ADDR  VARCHAR(255),
   MODIFIED_BY          VARCHAR(255),
   MODIFIED_DATE        TIMESTAMP,
   MODIFIED_REMOTE_ADDR VARCHAR(255),
   PRIMARY KEY (CODE_ITEM_ID)
);

CREATE SEQUENCE CODE_ITEM_DICTIONARY_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE PRUNUS_BIZ_CODE_ITEM_DICTIONARY
(
   CODE_ITEM_DICTIONARY_ID BIGINT NOT NULL,
   TITLE                   VARCHAR(100),
   SHORT_TITLE             VARCHAR(100),
   LANGUAGE                VARCHAR(10),
   CODE_ITEM_ID            BIGINT,
   PRIMARY KEY (CODE_ITEM_DICTIONARY_ID)
);

