CREATE SEQUENCE MENU_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE PRUNUS_BIZ_MENU
(
    MENU_ID        BIGINT NOT NULL,
    PARENT_MENU_ID BIGINT,
    TENANT         VARCHAR(50) NOT NULL,
    NAME           VARCHAR(50) NOT NULL,
    ICON           VARCHAR(50),
    ACTIVE         BOOLEAN NOT NULL,
    SORT_ORDER     INTEGER NOT NULL,
    PRIMARY KEY (MENU_ID)
);

CREATE SEQUENCE MENU_DICTIONARY_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE PRUNUS_BIZ_MENU_DICTIONARY
(
    MENU_DICTIONARY_ID BIGINT NOT NULL,
    MENU_ID            BIGINT,
    TITLE              VARCHAR(100),
    LANGUAGE           VARCHAR(10),
    PRIMARY KEY (MENU_DICTIONARY_ID)
);
ALTER TABLE PRUNUS_BIZ_MENU_DICTIONARY
    ADD CONSTRAINT PRUNUS_BIZ_MENU_DICTIONARY_UNIQUE_01 UNIQUE (MENU_ID, LANGUAGE);

CREATE SEQUENCE MENU_PROGRAM_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE PRUNUS_BIZ_MENU_PROGRAM
(
    PROGRAM_ID   BIGINT NOT NULL,
    MENU_ID      BIGINT,
    PROGRAM_TYPE VARCHAR(50),
    URL          VARCHAR(300) NOT NULL,
    ACTIVE       BOOLEAN NOT NULL,
    PRIMARY KEY (PROGRAM_ID)
);

