CREATE SEQUENCE RESOURCE_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE PRUNUS_BIZ_RESOURCE
(
    RESOURCE_ID          BIGINT NOT NULL,
    TENANT               VARCHAR(50) NOT NULL,
    NAME                 VARCHAR(200) NOT NULL,
    TYPE                 VARCHAR(20) NOT NULL,
    ACTIVE               BOOLEAN NOT NULL,
    CREATED_BY           VARCHAR(255),
    CREATED_DATE         TIMESTAMP,
    CREATED_REMOTE_ADDR  VARCHAR(255),
    MODIFIED_BY          VARCHAR(255),
    MODIFIED_DATE        TIMESTAMP,
    MODIFIED_REMOTE_ADDR VARCHAR(255),
    PRIMARY KEY (RESOURCE_ID)
);

CREATE SEQUENCE RESOURCE_METHOD_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE PRUNUS_BIZ_RESOURCE_METHOD
(
    RESOURCE_METHOD_ID BIGINT NOT NULL,
    RESOURCE_ID        BIGINT,
    NAME               VARCHAR(100) NOT NULL,
    INDEX              INTEGER NOT NULL,
    PRIMARY KEY (RESOURCE_METHOD_ID)
);

CREATE SEQUENCE RESOURCE_REQUEST_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE PRUNUS_BIZ_RESOURCE_REQUEST
(
    RESOURCE_REQUEST_ID BIGINT NOT NULL,
    RESOURCE_ID         BIGINT,
    HTTP_METHODS        VARCHAR(20) NOT NULL,
    URL_PATTERNS        VARCHAR(100) NOT NULL,
    PRIMARY KEY (RESOURCE_REQUEST_ID)
);
