CREATE TABLE PRUNUS_ACCOUNT
(
    TENANT                    VARCHAR(50) NOT NULL,
    USERNAME                  VARCHAR(100) NOT NULL,
    PASSWORD                  VARCHAR(500) NOT NULL,
    LOCKED                    BOOLEAN,
    CREDENTIALS_EXPIRED       BOOLEAN,
    ACCOUNT_EXPIRED           BOOLEAN,
    DISABLED                  BOOLEAN,
    LAST_PASSWORD_CHANGE_DATE DATE,
    FAILED_ATTEMPTS           INTEGER,
    LOCK_TIME                 TIMESTAMP,
    MFA_ENABLED               BOOLEAN,
    SECRET                    VARCHAR(512),
    OPT                       VARCHAR(255),
    PRIMARY KEY (TENANT, USERNAME)
);

CREATE TABLE PRUNUS_ACCOUNT_TOKEN
(
    UUID          VARCHAR(36) NOT NULL,
    TENANT        VARCHAR(50) NOT NULL,
    USERNAME      VARCHAR(100) NOT NULL,
    ACCESS_TOKEN  CLOB NOT NULL,
    REFRESH_TOKEN VARCHAR(255) NOT NULL,
    DEVICE        VARCHAR(30),
    PRIMARY KEY (TENANT, UUID, USERNAME)
);
